import { linter, Diagnostic } from '@codemirror/lint';
import { CompletionContext, CompletionResult } from '@codemirror/autocomplete';

export const customCompletion = (context: CompletionContext): CompletionResult | null => {
    const word = context.matchBefore(/\w*/);
    if (!word) return null;
    return {
        from: word.from,
        options: [
            // Java Keywords
            // { label: "abstract", type: "keyword" },
            { label: "assert", type: "keyword" },
            { label: "boolean", type: "type" },
            { label: "break", type: "keyword" },
            { label: "byte", type: "type" },
            { label: "case", type: "keyword" },
            { label: "catch", type: "keyword" },
            { label: "char", type: "type" },
            { label: "class", type: "keyword", info: "Define a class" },
            { label: "const", type: "keyword" },
            { label: "continue", type: "keyword" },
            { label: "default", type: "keyword" },
            { label: "do", type: "keyword" },
            { label: "double", type: "type" },
            { label: "else", type: "keyword" },
            { label: "enum", type: "keyword" },
            { label: "extends", type: "keyword" },
            { label: "final", type: "keyword" },
            { label: "finally", type: "keyword" },
            { label: "float", type: "type" },
            { label: "for", type: "keyword" },
            { label: "goto", type: "keyword" },
            { label: "if", type: "keyword" },
            { label: "implements", type: "keyword" },
            // { label: "import", type: "keyword" },
            { label: "instanceof", type: "keyword" },
            { label: "int", type: "type" },
            { label: "interface", type: "keyword" },
            { label: "long", type: "type" },
            { label: "native", type: "keyword" },
            { label: "new", type: "keyword" },
            { label: "package", type: "keyword" },
            { label: "private", type: "keyword" },
            { label: "protected", type: "keyword" },
            { label: "public", type: "keyword" },
            { label: "return", type: "keyword" },
            { label: "short", type: "type" },
            { label: "static", type: "keyword" },
            { label: "strictfp", type: "keyword" },
            // { label: "super", type: "keyword" },
            { label: "switch", type: "keyword" },
            // { label: "synchronized", type: "keyword" },
            { label: "this", type: "keyword" },
            { label: "throw", type: "keyword" },
            { label: "throws", type: "keyword" },
            // { label: "transient", type: "keyword" },
            { label: "try", type: "keyword" },
            { label: "void", type: "type" },
            { label: "volatile", type: "keyword" },
            { label: "while", type: "keyword" },

            // Common types
            { label: "@new", type: "type" },
            { label: "@println", type: "type" },
            { label: "@print", type: "type" },
            { label: "String", type: "type" },
            { label: "Integer", type: "type" },
            { label: "Double", type: "type" },
            { label: "Float", type: "type" },
            { label: "Long", type: "type" },
            { label: "Short", type: "type" },
            { label: "Byte", type: "type" },
            { label: "Boolean", type: "type" },
            { label: "Character", type: "type" },
            { label: "Object", type: "type" },
            { label: "ArrayList", type: "type" },
            { label: "List", type: "type" },
            { label: "Map", type: "type" },
            { label: "HashMap", type: "type" },
            { label: "Set", type: "type" },
            // { label: "HashSet", type: "type" },
            // { label: "Vector", type: "type" },
            // { label: "Queue", type: "type" },
            // { label: "Deque", type: "type" },

            // Common methods/functions
            // { label: "System.out.println", type: "function", apply: "System.out.println(\"\"\);" },
            // { label: "System.out.print", type: "function", apply: "System.out.print(\"\"\);" },
            // { label: "System.err.println", type: "function", apply: "System.err.println(\"\"\);" },
            // { label: "main", type: "function", apply: "public static void main(String[] args) {\n\n}" },
            { label: "toString", type: "function" },
            { label: "equals", type: "function" },
            // { label: "hashCode", type: "function" },
            // { label: "getClass", type: "function" },
            // { label: "clone", type: "function" },
            // { label: "finalize", type: "function" },

            // Common annotations
            // { label: "@Override", type: "annotation" },
            { label: "@run", type: "annotation" },
            { label: "@onload", type: "annotation" },
            { label: "@FFunction", type: "annotation" },
            // { label: "@Deprecated", type: "annotation" },
            // { label: "@SuppressWarnings", type: "annotation" },
            // { label: "@FunctionalInterface", type: "annotation" },
            // { label: "@SafeVarargs", type: "annotation" },

            // Common exceptions
            { label: "Exception", type: "type" },
            // { label: "RuntimeException", type: "type" },
            // { label: "NullPointerException", type: "type" },
            // { label: "IllegalArgumentException", type: "type" },
            // { label: "IOException", type: "type" },
            // { label: "FileNotFoundException", type: "type" },
            // { label: "ArrayIndexOutOfBoundsException", type: "type" },
            // { label: "ClassNotFoundException", type: "type" },
            // { label: "IndexOutOfBoundsException", type: "type" },
            // { label: "NumberFormatException", type: "type" },
            // { label: "InterruptedException", type: "type" },

            // Common packages
            // { label: "java.util", type: "namespace" },
            // { label: "java.io", type: "namespace" },
            // { label: "java.lang", type: "namespace" },
            // { label: "java.math", type: "namespace" },
            // { label: "java.net", type: "namespace" },
            // { label: "java.time", type: "namespace" },
            // { label: "java.nio", type: "namespace" },
            // { label: "java.sql", type: "namespace" },
            // { label: "java.text", type: "namespace" },
            // { label: "java.awt", type: "namespace" },

            // Spring Boot annotations
            // { label: "@SpringBootApplication", type: "annotation", info: "Main Spring Boot application annotation" },
            // { label: "@RestController", type: "annotation", info: "Marks class as REST controller" },
            // { label: "@Controller", type: "annotation", info: "Marks class as Spring MVC controller" },
            // { label: "@RequestMapping", type: "annotation", info: "Maps HTTP requests to handler methods" },
            // { label: "@GetMapping", type: "annotation", info: "Maps HTTP GET requests" },
            // { label: "@PostMapping", type: "annotation", info: "Maps HTTP POST requests" },
            // { label: "@PutMapping", type: "annotation", info: "Maps HTTP PUT requests" },
            // { label: "@DeleteMapping", type: "annotation", info: "Maps HTTP DELETE requests" },
            // { label: "@PatchMapping", type: "annotation", info: "Maps HTTP PATCH requests" },
            // { label: "@Autowired", type: "annotation", info: "Marks a dependency to be injected" },
            // { label: "@Service", type: "annotation", info: "Marks class as service" },
            // { label: "@Component", type: "annotation", info: "Marks class as component" },
            // { label: "@Repository", type: "annotation", info: "Marks class as repository" },
            // { label: "@Configuration", type: "annotation", info: "Marks class as configuration" },
            // { label: "@Value", type: "annotation", info: "Injects property value" },
            // { label: "@Bean", type: "annotation", info: "Marks method as bean producer" },
            // { label: "@Qualifier", type: "annotation", info: "Specifies which bean to inject" },
            // { label: "@RequestBody", type: "annotation", info: "Maps request body to method parameter" },
            // { label: "@ResponseBody", type: "annotation", info: "Maps return value to response body" },
            // { label: "@PathVariable", type: "annotation", info: "Maps URI template variable to method parameter" },
            // { label: "@RequestParam", type: "annotation", info: "Maps request parameter to method parameter" },
            // { label: "@CrossOrigin", type: "annotation", info: "Enables CORS on controller or method" },
            // { label: "@EnableAutoConfiguration", type: "annotation", info: "Enables Spring Boot auto-configuration" },
            // { label: "@Entity", type: "annotation", info: "Marks class as JPA entity" },
            // { label: "@Table", type: "annotation", info: "Specifies table for JPA entity" },
            // { label: "@Id", type: "annotation", info: "Marks field as primary key" },
            // { label: "@GeneratedValue", type: "annotation", info: "Specifies primary key generation strategy" },
            // { label: "@Column", type: "annotation", info: "Specifies column mapping for JPA entity" },
           // { label: "@Transactional", type: "annotation", info: "Marks method/class as transactional" },

            // Spring Boot classes
            // { label: "SpringApplication.run", type: "function", apply: "SpringApplication.run(Application.class, args);" },
            // { label: "ResponseEntity", type: "type", info: "Represents HTTP response" },
            // { label: "RestTemplate", type: "type", info: "Client to perform HTTP requests" },
            // { label: "ApplicationContext", type: "type", info: "Spring application context" },
            // { label: "Environment", type: "type", info: "Spring environment abstraction" },
            // { label: "CommandLineRunner", type: "type", info: "Callback for application startup" },
            // { label: "DataSource", type: "type", info: "Database connection pool" },
            // { label: "JpaRepository", type: "type", info: "Spring Data JPA repository" },
            // { label: "CrudRepository", type: "type", info: "Spring Data CRUD repository" },
            // { label: "Pageable", type: "type", info: "Pagination information" },
            // { label: "Page", type: "type", info: "Page of data" },
            // { label: "Sort", type: "type", info: "Sorting information" },
            // { label: "Model", type: "type", info: "Spring MVC model" },
            // { label: "BindingResult", type: "type", info: "Validation result" },
            // { label: "HttpStatus", type: "type", info: "HTTP status codes" },
            // { label: "MultipartFile", type: "type", info: "Uploaded file abstraction" },
            // { label: "Filter", type: "type", info: "Servlet filter" },
            // { label: "HandlerInterceptor", type: "type", info: "Spring MVC interceptor" },
            // { label: "WebMvcConfigurer", type: "type", info: "Spring MVC configuration" },
            // { label: "ExceptionHandler", type: "type", info: "Exception handler annotation" },
            // Add more as needed...
        ]
    };
}